return {
  {
    "zaldih/themery.nvim",
    config = function()
      require("themery").setup({
        themes = {
          { name = "Catppuccin Mocha",    colorscheme = "catppuccin-mocha" },
          { name = "Catppuccin Macchiato",colorscheme = "catppuccin-macchiato" },
          { name = "Catppuccin Frappe",   colorscheme = "catppuccin-frappe" },
          { name = "Catppuccin Latte",    colorscheme = "catppuccin-latte" },
          { name = "Tokyo Night",         colorscheme = "tokyonight" },
          { name = "Tokyo Night Storm",   colorscheme = "tokyonight-storm" },
          { name = "Tokyo Night Day",     colorscheme = "tokyonight-day" },
          { name = "Rose Pine",           colorscheme = "rose-pine" },
          { name = "Rose Pine Moon",      colorscheme = "rose-pine-moon" },
          { name = "Rose Pine Dawn",      colorscheme = "rose-pine-dawn" },
          { name = "Kanagawa Wave",       colorscheme = "kanagawa-wave" },
          { name = "Kanagawa Dragon",     colorscheme = "kanagawa-dragon" },
          { name = "Gruvbox Dark",        colorscheme = "gruvbox" },
          { name = "Everforest",          colorscheme = "everforest" },
          { name = "Nord",                colorscheme = "nord" },
          { name = "Nightfox",            colorscheme = "nightfox" },
          { name = "Carbonfox",           colorscheme = "carbonfox" },
          { name = "Dayfox",              colorscheme = "dayfox" },
          { name = "Onedark",             colorscheme = "onedark" },
          { name = "Vitesse",          colorscheme = "vitesse", before = [[require("vitesse").setup({})]] },
          { name = "Dracula",          colorscheme = "dracula" },
          { name = "Monokai Pro",      colorscheme = "monokai-pro" },
          { name = "Material Darker",  colorscheme = "material-darker" },
          { name = "Material Oceanic", colorscheme = "material-oceanic" },
          { name = "Solarized Dark",   colorscheme = "solarized" },
          { name = "GitHub Dark",      colorscheme = "github_dark" },
          { name = "GitHub Light",     colorscheme = "github_light" },
          { name = "Ayu Dark",         colorscheme = "ayu-dark" },
          { name = "Ayu Light",        colorscheme = "ayu-light" },
          { name = "Sonokai",          colorscheme = "sonokai" },
          { name = "Moonfly",          colorscheme = "moonfly" },
          { name = "Nightfly",         colorscheme = "nightfly" },
        },
        livePreview = true,
      })
      vim.keymap.set("n", "<leader>tc", "<cmd>Themery<cr>", { desc = "Theme picker" })
    end,
  },
  { "folke/tokyonight.nvim",             lazy = true },
  { "rose-pine/neovim",                  name = "rose-pine", lazy = true },
  { "rebelot/kanagawa.nvim",             lazy = true },
  { "ellisonleao/gruvbox.nvim",          lazy = true },
  { "neanias/everforest-nvim",           lazy = true },
  { "shaunsingh/nord.nvim",              lazy = true },
  { "EdenEast/nightfox.nvim",            lazy = true },
  { "navarasu/onedark.nvim",             lazy = true },
  { "2nthony/vitesse.nvim",              lazy = true, dependencies = { "tjdevries/colorbuddy.nvim" } },
  { "Mofiqul/dracula.nvim",             lazy = true },
  { "loctvl842/monokai-pro.nvim",       lazy = true },
  { "marko-cerovac/material.nvim",      lazy = true },
  { "ishan9299/nvim-solarized-lua",     lazy = true },
  { "projekt0n/github-nvim-theme",      lazy = true },
  { "Shatur/neovim-ayu",               lazy = true },
  { "sainnhe/sonokai",                  lazy = true },
  { "bluz71/vim-moonfly-colors",        lazy = true, name = "moonfly" },
  { "bluz71/vim-nightfly-colors",       lazy = true, name = "nightfly" },
}
